#ifndef VIRTUALINPUT_GLOBAL_H
#define VIRTUALINPUT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(VIRTUALINPUT_LIBRARY)
#  define VIRTUALINPUTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define VIRTUALINPUTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // VIRTUALINPUT_GLOBAL_H
